import MetaSearchAgent from '@/lib/search/metaSearchAgent';
import prompts from '../prompts';
import { LegalAgentAdapter } from './legalAgentAdapter';

export const searchHandlers: Record<string, MetaSearchAgent> = {
  webSearch: new MetaSearchAgent({
    activeEngines: ['searxng'],
    queryGeneratorPrompt: prompts.webSearchRetrieverPrompt,
    responsePrompt: prompts.webSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: true,
    isMultiQuery: false,
  }),
  academicSearch: new MetaSearchAgent({
    activeEngines: ['google', 'bing'],
    queryGeneratorPrompt: prompts.academicSearchRetrieverPrompt,
    responsePrompt: prompts.academicSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
    isMultiQuery: false,
  }),
  deepLegalResearch: new MetaSearchAgent({
    activeEngines: ['google', 'bing', 'searxng'],
    queryGeneratorPrompt: prompts.deepResearchRetrieverPrompt,
    responsePrompt: prompts.deepResearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.2,
    searchWeb: true,
    summarizer: false,
    isMultiQuery: true,
  }),
  writingAssistant: new MetaSearchAgent({
    activeEngines: [],
    queryGeneratorPrompt: '',
    responsePrompt: prompts.writingAssistantPrompt,
    rerank: true,
    rerankThreshold: 0,
    searchWeb: false,
    summarizer: false,
  }),
  wolframAlphaSearch: new MetaSearchAgent({
    activeEngines: ['wolframalpha'],
    queryGeneratorPrompt: prompts.wolframAlphaSearchRetrieverPrompt,
    responsePrompt: prompts.wolframAlphaSearchResponsePrompt,
    rerank: false,
    rerankThreshold: 0,
    searchWeb: true,
    summarizer: false,
    isMultiQuery: false,
  }),
  redditSearch: new MetaSearchAgent({
    activeEngines: ['reddit'],
    queryGeneratorPrompt: prompts.redditSearchRetrieverPrompt,
    responsePrompt: prompts.redditSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
    isMultiQuery: false,
  }),
};
